dev:
  protected: true
  allowed_ip: [127.0.0.1]
  protected_route: secure
  format: [yml, json, xml]
  models:
    user:
      method_for_query: findActives
    non_active_model:
      method_for_query: ~