ws_entry:
  url: /api/:model.:sf_format
  class: sfRequestRoute
  param: { module: sfRestWebService, action: entry, sf_format: xml }
  requirements:
    id: \d+
    sf_method: [GET, POST]

ws_resource:
  url:  /api/:model/:id.:sf_format
  class: sfRequestRoute
  param: { module: sfRestWebService, action: resource, sf_format: xml }
  requirements:
    id: \d+
    sf_method: [GET, PUT, DELETE]

ws_500:
  url:  /api/error
  param: { module: sfRestWebService, action: 500 }